fields:
  address1:
    field_group_id: 3
    label: 'Address 1:'
    as: 'string'
    maxlength: '100'
    required: false
    disabled: false
    hint: ''
    placeholder: ''
  address2:
    field_group_id: 3
    label: 'Address 2:'
    as: 'string'
    maxlength: '100'
    required: false
    disabled: false
    hint: ''
    placeholder: ''