fields:
  businessName:
    field_group_id: <%=CONTACT_FIELDS_GROUP_ID%>
    label: 'Business Name:'
    as: 'string'
    maxlength: '100'
    required: false
    disabled: false
    hint: ''
    placeholder: ''
  dateOfBirth:
    field_group_id: <%=CONTACT_FIELDS_GROUP_ID%>
    label: 'Date Of Birth:'
    as: 'date'
    required: false
    disabled: false
    hint: ''
    placeholder: ''
  preferredLanguage:
    field_group_id: <%=CONTACT_FIELDS_GROUP_ID%>
    label: 'Preferred Language:'
    as: 'check_boxes'
    collection_string: English|Spanish
    required: false
    disabled: false
    hint: ''
    placeholder: ''
  category:
    field_group_id: <%=CONTACT_FIELDS_GROUP_ID%>
    label: 'Category:'
    as: 'check_boxes'
    collection_string: Member|Service Recipient|Donor|Volunteer
    required: false
    disabled: false
    hint: ''
    placeholder: ''